HybridEncoder:
  act: silu
  depth_mult: 1
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: gelu
  eval_spatial_size:
  - 640
  - 640
  expansion: 1.0
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  in_channels:
  - 512
  - 1024
  - 2048
  nhead: 8
  num_encoder_layers: 1
  pe_temperature: 10000
  use_encoder_idx:
  - 2
PResNet:
  depth: 50
  freeze_at: 0
  freeze_norm: true
  num_stages: 4
  pretrained: true
  return_idx:
  - 1
  - 2
  - 3
  variant: d
RTDETR:
  backbone: PResNet
  decoder: RTDETRTransformer
  encoder: HybridEncoder
  multi_scale:
  - 480
  - 512
  - 544
  - 576
  - 608
  - 640
  - 640
  - 640
  - 672
  - 704
  - 736
  - 768
  - 800
RTDETRPostProcessor:
  num_top_queries: 300
RTDETRTransformer:
  eval_idx: -1
  eval_spatial_size:
  - 640
  - 640
  feat_channels:
  - 256
  - 256
  - 256
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  num_decoder_layers: 6
  num_denoising: 100
  num_levels: 3
  num_queries: 300
SetCriterion:
  alpha: 0.75
  gamma: 2.0
  losses:
  - vfl
  - boxes
  matcher:
    alpha: 0.25
    gamma: 2.0
    type: HungarianMatcher
    weight_dict:
      cost_bbox: 5
      cost_class: 2
      cost_giou: 2
  weight_dict:
    loss_bbox: 5
    loss_giou: 2
    loss_vfl: 1
checkpoint_step: 0.1
clip_max_norm: 0.1
criterion: SetCriterion
ema:
  decay: 0.9999
  type: ModelEMA
  warmups: 2000
epoches: 500
find_unused_parameters: true
lr_scheduler:
  gamma: 0.1
  milestones:
  - 1000
  type: MultiStepLR
model: RTDETR
num_classes: 2
optimizer:
  betas:
  - 0.9
  - 0.999
  lr: 0.0001
  params:
  - lr: 1.0e-05
    params: backbone
  - params: ^(?=.*encoder(?=.*bias|.*norm.*weight)).*$
    weight_decay: 0.0
  - params: ^(?=.*decoder(?=.*bias|.*norm.*weight)).*$
    weight_decay: 0.0
  type: AdamW
  weight_decay: 0.0001
output_dir: ./output/rtdetr_r50vd_6x_coco
postprocessor: RTDETRPostProcessor
remap_mscoco_category: false
scaler:
  enabled: true
  type: GradScaler
sync_bn: true
task: detection
train_dataloader:
  batch_size: 48
  collate_fn: default_collate_fn
  dataset:
    ann_file: /mnt/nvstorage/gis/seedling/data/tiled_coco/640/images/train/train_coco.json
    img_folder: /mnt/nvstorage/gis/seedling/data/tiled_coco/640/images/train/
    return_masks: false
    transforms:
      ops:
      - p: 0.5
        type: RandomPhotometricDistort
      - fill: 0
        type: RandomZoomOut
      - p: 0.8
        type: RandomIoUCrop
      - min_size: 1
        type: SanitizeBoundingBox
      - type: RandomHorizontalFlip
      - size:
        - 640
        - 640
        type: Resize
      - type: ToImageTensor
      - type: ConvertDtype
      - min_size: 1
        type: SanitizeBoundingBox
      - normalize: true
        out_fmt: cxcywh
        type: ConvertBox
      type: Compose
    type: CocoDetection
  drop_last: true
  num_workers: 8
  shuffle: true
  type: DataLoader
use_amp: false
use_ema: true
use_focal_loss: true
val_dataloader:
  batch_size: 48
  collate_fn: default_collate_fn
  dataset:
    ann_file: /mnt/nvstorage/gis/seedling/data/tiled_coco/640/images/val/val_coco.json
    img_folder: /mnt/nvstorage/gis/seedling/data/tiled_coco/640/images/val/
    transforms:
      ops:
      - size:
        - 640
        - 640
        type: Resize
      - type: ToImageTensor
      - type: ConvertDtype
      type: Compose
    type: CocoDetection
  drop_last: false
  num_workers: 8
  shuffle: false
  type: DataLoader
