
__include__: [
  '../dataset/coco_detection_2560.yml',
  '../runtime.yml',
  './include/dataloader_2560.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd_2560.yml',
]


output_dir: ./output/rtdetr_r50vd_6x_coco_2560